default: &default
  shopify_app_name: "sellist shopify local app"
  shopify_app_key: fe679c7e6df44d892efc0ae90a4531bf
  shopify_app_secret: d07b2fbf7df3994cebcb6af532dc16d7

development:
  <<: *default
  site_url: "http://localhost:3001"

production: &production
  <<: *default
  site_url: "http://sellist.io"
  shopify_app_name: "sellist shopify app"
  shopify_app_key: 14c825c14c5fee1a66dc49ebece0a1e9
  shopify_app_secret: 3fe541cb9c14d5fbda34bd73f8fc6dfe
